#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif

include $(DEVKITARM)/ds_rules

export TARGET		:=	angband
export TOPDIR		:=	$(CURDIR)


.PHONY: checkarm7 checkarm9

include Makefile.inc

export BASEOBJS		:= $(BASEOBJS) 

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
all: checkarm7 checkarm9 $(TARGET).nds

#---------------------------------------------------------------------------------
$(TARGET).nds	:	$(TARGET).arm7.elf $(TARGET).arm9.elf
	ndstool	-c $(TARGET).nds -7 $(TARGET).arm7.elf -9 $(TARGET).arm9.elf

#---------------------------------------------------------------------------------
checkarm7 $(TARGET).arm7.elf:
	$(MAKE) -f Makefile.nds.arm7
	
#---------------------------------------------------------------------------------
checkarm9 $(TARGET).arm9.elf:
	$(MAKE) -f Makefile.nds.arm9

#---------------------------------------------------------------------------------
clean:
	$(MAKE) -f Makefile.nds.arm9 clean
	$(MAKE) -f Makefile.nds.arm7 clean
	rm -f $(TARGET).nds $(TARGET).arm7 $(TARGET).arm9
